name: Record release download counts (daily)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "12 2 * * *"   # daily at 02:12 UTC

permissions:
  contents: write

jobs:
  record:
    runs-on: ubuntu-latest
    env:
      REPO: soundshow-app/soundshow-downloads   # or use: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect counts
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          date_utc=$(date -u +%F)
          mkdir -p stats
          repo_file="stats/${REPO#*/}.csv"
          if [ ! -s "$repo_file" ]; then
            echo "date,tag,asset,download_count" > "$repo_file"
          fi

          # Call API and capture HTTP status
          http_code=$(curl -sS -w "%{http_code}" -o releases.json \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/repos/$REPO/releases?per_page=100")

          if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
            echo "GitHub API HTTP $http_code"
            cat releases.json
            exit 1
          fi

          # Fail if the payload isn't an array (e.g., Not Found / rate-limit)
          if jq -e 'type != "array"' releases.json >/dev/null; then
            echo "Unexpected API response (not an array):"
            cat releases.json
            exit 1
          fi

          # Append one row per asset
          jq -r --arg d "$date_utc" '
            .[] as $r
            | ($r.assets // [])[]
            | [$d, ($r.tag_name // ""), .name, (.download_count // 0)]
            | @csv
          ' releases.json >> "$repo_file"

      - name: Commit stats
        shell: bash
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add stats/*.csv || true
          git commit -m "stats: $(date -u +%F)" || exit 0
          git push
